-- subjects 테이블 + 테스트 데이터 + 익명 읽기 정책
create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  code text unique not null,
  created_at timestamptz default now()
);

insert into public.subjects (name, code)
values ('9급 국어', 'korean')
on conflict (code) do nothing;

alter table public.subjects enable row level security;

drop policy if exists "subjects_public_read" on public.subjects;
create policy "subjects_public_read"
  on public.subjects
  for select
  to anon, authenticated
  using (true);
